<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.0" language="de" sourcelanguage="">
<context>
    <name>Cartogram</name>
    <message>
        <location filename="../cartogram.py" line="112"/>
        <source>&amp;cartogram3</source>
        <translation type="obsolete">&amp;Kartogramm</translation>
    </message>
    <message>
        <location filename="../cartogram.py" line="209"/>
        <source>Compute cartogram</source>
        <translation>Kartogramm berechnen</translation>
    </message>
    <message>
        <location filename="../cartogram.py" line="111"/>
        <source>&amp;Cartogram</source>
        <translation>&amp;Kartogramm</translation>
    </message>
    <message>
        <location filename="../cartogram.py" line="485"/>
        <source>Error</source>
        <translation>Fehler</translation>
    </message>
    <message>
        <location filename="../cartogram.py" line="279"/>
        <source>You need at least one polygon vector layer to create a cartogram.</source>
        <translation>Für die Berechnung eines Kartogramms ist mindestens ein Polygon-Vektorlayer erforderlich.</translation>
    </message>
    <message>
        <location filename="../cartogram.py" line="357"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
    <message>
        <location filename="../cartogram.py" line="466"/>
        <source>cartogram3 successfully finished computing a cartogram for field &#xe2;&#x80;&#x98;{fieldName}&#xe2;&#x80;&#x99; after {iterations} iterations with {avgError:.2%} average error remaining.</source>
        <translation>cartogram3: Kartogrammberechnung für Attribut ‚{fieldName}‘ nach {iterations} Durchgängen erfolgreich, verbleibender mittlerer Fehler: {avgError:.2%}.</translation>
    </message>
    <message>
        <location filename="../cartogram.py" line="477"/>
        <source>cartogram3 computation cancelled by user</source>
        <translation>cartogram3: Berechnung vom Benutzer abgebrochen</translation>
    </message>
    <message>
        <location filename="../cartogram.py" line="485"/>
        <source>An error occurred during cartogram creation. Please see the &#xe2;&#x80;&#x9c;Plugins&#xe2;&#x80;&#x9d; section of the message log for details.</source>
        <translation>Fehler bei der Kartogrammberechnung. Einzelheiten im Fehlerprotokoll unter „Plugins“.
</translation>
    </message>
    <message>
        <location filename="../cartogram.py" line="286"/>
        <source>Add sample dataset</source>
        <translation>Beispieldatensatz hinzufügen</translation>
    </message>
</context>
<context>
    <name>CartogramDialog</name>
    <message>
        <location filename="../cartogram_dialog.ui" line="14"/>
        <source>cartogram3</source>
        <translation>cartogram3</translation>
    </message>
    <message>
        <location filename="../cartogram_dialog.ui" line="20"/>
        <source>Input layer:</source>
        <translation>Input Layer:</translation>
    </message>
    <message>
        <location filename="../cartogram_dialog.ui" line="27"/>
        <source>Field(s):</source>
        <translation>Attribut(e):</translation>
    </message>
    <message>
        <location filename="../cartogram_dialog.ui" line="41"/>
        <source>Stop conditions:</source>
        <translation>Bedingungen:</translation>
    </message>
    <message>
        <location filename="../cartogram_dialog.ui" line="57"/>
        <source>max. number of iterations:</source>
        <translation>max. Durchgänge:</translation>
    </message>
    <message>
        <location filename="../cartogram_dialog.ui" line="74"/>
        <source>max. average error:</source>
        <translation>max. mittlerer Fehler:</translation>
    </message>
    <message>
        <location filename="../cartogram_dialog.ui" line="81"/>
        <source>%</source>
        <translation>%</translation>
    </message>
    <message>
        <location filename="../cartogram_dialog.ui" line="94"/>
        <source>Calculation stops as soon as one condition is met.</source>
        <translation>Die Berechnung endet, sobald eine Bedingung erfüllt ist.</translation>
    </message>
</context>
<context>
    <name>CartogramWorker</name>
    <message>
        <location filename="../cartogram_worker.py" line="92"/>
        <source>Iteration {i}/{mI} for field &#xe2;&#x80;&#x98;{fN}&#xe2;&#x80;&#x99;</source>
        <translation>Durchgang {i}/{mI} für Attribut ‚{fN}‘</translation>
    </message>
</context>
</TS>
